on:
  workflow_dispatch:
  push:
    branches:
    - main
    
permissions:
  id-token: write
  contents: read

env:
  IMAGE_TAG: ${{ github.sha }}
  BACKEND_REPOSITORY: devops-na-nuvem-week/production/backend
  FRONTEND_REPOSITORY: devops-na-nuvem-week/production/frontend

jobs:
  backend_deployment:
    name: Deploying Backend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checking Code Out
      uses: actions/checkout@v4

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -f ./backend/YoutubeLiveApp/Dockerfile -t $REGISTRY/$BACKEND_REPOSITORY:$IMAGE_TAG ./backend/YoutubeLiveApp/
        docker push $REGISTRY/$BACKEND_REPOSITORY:$IMAGE_TAG
    
    - name: Checking Out GitOps Repository
      uses: actions/checkout@v4
      with:
        repository: kenerry-serain/devops-na-nuvem-week-03-gitops
        token: ${{secrets.PAT}}

    - name: Kustomize Edit Image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        kustomize edit set image $REGISTRY/$BACKEND_REPOSITORY=$REGISTRY/$BACKEND_REPOSITORY:$IMAGE_TAG

    - name: Committing Changes
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./kustomization.yml
          git commit -m "[GitOps] Changing Image To $REGISTRY/$BACKEND_REPOSITORY:$IMAGE_TAG"
          git push
